services:
  simplecontainerapp:
    container_name: securecontainerapp
    build: .
    image: simpleloginandregisterapp:v1
    ports:
      - 80:80
    expose:
      - 80  
    networks:
     - internalnet  
networks:
  internalnet:
    driver: bridge     